## Welcome to StableRLS
This first tutorial shows how to:
1. import the package
2. create a FMU from your simulink model
3. create and simulate the environment

The basic config file has three sections: General, FMU and Reinforcement Learning. By default the parameters of all sections will be available within the environment class. The documentation provides more information about all available config options. To get started we need to set:
- FMU_path : location the FMU is stored. If the FMU is created this is also used as target location.
- stop_time : when the time is reached the simulation/ episode is terminated.
- dt : we run a fixed step simulation and this is the timestep.

---

```
[General]

[FMU]
FMU_path = 00-Simulink_Linux.fmu
stop_time =  1
dt = 0.5

[Reinforcement Learning]
```

In [8]:
# this contains the environment class
import stablerls.gymFMU as gymFMU
# this will read our config file
import stablerls.configreader as cfg_reader

import numpy as np
import logging
# normally we dont recommend the Info logging but here its used for demonstation
logging.basicConfig(level=logging.INFO)

For simplicity we already included the compiled FMU models for Linux and Windows. However, if you own Matlab you can compile the *.slx models on your own. If you want to compile the model you can keep the default FMU_path in the config file. Otherwise please change it to 00-Simulink_Windows.fmu or 00-Simulink_Linux.fmu depending on your operating system.

In [20]:
# First of all we have to read the config file
config = cfg_reader.configreader('00-config.cfg')

# if we want to we can compile the simulink model. 
# Matlab and Matlab Engine for python is required!
if True:
    import stablerls.createFMU as createFMU
    createFMU.createFMU(config,'SimulinkExample00.slx')

> In getports>create_input_bus (line 220)
In getports>create_input_bus (line 228)
In getports>create_input_bus (line 228)
In getports (line 67)
Setting System Target to FMU Co-Simulation for model 'SimulinkExample02'.
Setting Hardware Implementation > Device Type to 'MATLAB Host' for model 'SimulinkExample02'.
### 'GenerateComments' is disabled for Co-Simulation Standalone FMU Export.

Build Summary

Top model targets built:

Model              Action                        Rebuild Reason                                    
SimulinkExample02  Code generated and compiled.  Code generation information file does not exist.  

1 of 1 models built (0 models already up to date)
Build duration: 0h 0m 5.3323s
### Model was successfully exported to co-simulation standalone FMU: '/home/cao2851/git/stablerls/Examples/SimulinkExample02.fmu'.


The FMU is available now and the default options of the StableRLS gymnasium environment are sufficient to run the first simulation.

In [21]:
# create instance of the model
env = gymFMU.StableRLS(config)

# default reset call bevor the simulation starts
obs = env.reset()

# we wont change the action 
action = np.array([1,2,3,4])

terminated = False
while not terminated:
    observation, reward, terminated, truncated, info  = env.step(action)
    print(action, observation, reward)
        
env.close()

INFO:stablerls.fmutools:Using: 00-Simulink_Linux.fmu
INFO:stablerls.fmutools:Unzipped in /tmp/tmpeeywyryw
INFO:stablerls.fmutools:Found Inputs access with corresponding number:
INFO:stablerls.fmutools: 0: Input3.TestSignal1
INFO:stablerls.fmutools: 1: Input3.TestSignal2
INFO:stablerls.fmutools: 2: Input2.TestSignal1
INFO:stablerls.fmutools: 3: Input2.TestSignal2
INFO:stablerls.fmutools: 4: Input1.Sum2
INFO:stablerls.fmutools: 5: Input1.Sum1
INFO:stablerls.fmutools: 6: Input.Test.TestSignal2
INFO:stablerls.fmutools: 7: Input.Test.TestSignal1
INFO:stablerls.fmutools: 8: Input.signal.TestSignal1
INFO:stablerls.fmutools: 9: Input.signal.TestSignal2
INFO:stablerls.fmutools: 10: Input.signal.Test.TestSignal1
INFO:stablerls.fmutools: 11: Input.signal.Test.TestSignal2
INFO:stablerls.fmutools: 12: Input.Test2.Sum3
INFO:stablerls.fmutools: 13: Input.Test2.Sum1
INFO:stablerls.fmutools: 14: Input.Test2.Sum2
INFO:stablerls.fmutools:Found Outputs access with corresponding number:
INFO:stablerls.fmut

[1 2 3 4] [1. 0.] 1
[1 2 3 4] [1. 0.] 1


The actions and outputs of each simulation/ episode are stored within the class. (Reset when we call the reset function)

In [ ]:
env.inputs

array([[0., 0., 0., 0.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
env.outputs

array([[0.],
       [3.],
       [3.]])